language: node_js
node_js:
- '0.10'
before_install: npm install -g mocha
before_script: npm install
after_success: npm publish
script: mocha -t 5000
env:
  global:
    secure: eglPZw7bJWrAQ+pcU5Y8QFhlwcFc5zcVlhqoUNSPX/IQyfy5FUaY4J854WaZ3kMxwnfnHkh/HGrkAN2X5CA1KnxT4l5b5FoSH7hsmtKvBMFPxCM9QpF7ob4Sq1ZrMDwzHPMpWXpCfcnY5BJgPM8BlK531cv/u0JWc097xqyzyKg=
deploy:
  provider: npm
  email: h.guzas@gmail.com
  api_key:
    secure: ZQbjUhY0gXseYfqiUfXIiH2+u5eLbyCjGRybqDB98EOd4VlXTVh4kkOVG6NX91Rc0pmEYtYmbGNq6QzoIDogR+OMGuv3qQhseRFpC6azTXnknnKPXJQj070dkh76rPy/Vn7pAxIqAMjmyvC4Cbb26oZ3RabINpeb2849pprTkEo=
  on:
    tags: true
    repo: emmorts/lolapi
